In [1]:
import torch
import torch.nn as nn
import torch.functional as F

In [2]:
import numpy as np

In [3]:
from torch.autograd import Variable

In [15]:
#creating tensors 
# wx+b
x = torch.tensor(3., requires_grad = True)
w = torch.tensor(4.,requires_grad = True)
b = torch.tensor(5., requires_grad = True)

In [16]:
#comptaional grapgh
y = w * x + b

In [17]:
# computing gradients
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(4.)
tensor(3.)
tensor(1.)


In [40]:
# basic autograd example
x = torch.randn(10,3)
y = torch.randn(10,2)


linear = nn.Linear(3,2)
print('w: ', linear.weight)
print('b: ', linear.bias)

#adding loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

#forward pass
pred = linear(x)

#compute loss
loss = criterion(pred,y)
print("Loss :", loss.item())

#backward pass
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# 1-step gradient descent.

for i in range(0,100):# arbitrary iteration to test optimizer affect the loss
    
    
    optimizer.step()

# To perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

print('w: ', linear.weight)
print('b: ', linear.bias)


w:  Parameter containing:
tensor([[-0.3057,  0.4254,  0.0472],
        [-0.4871, -0.3970,  0.1929]], requires_grad=True)
b:  Parameter containing:
tensor([0.2739, 0.0705], requires_grad=True)
Loss : 0.9766868948936462
dL/dw:  tensor([[-0.0831,  0.2246, -0.4304],
        [-0.5353, -0.2469,  0.1571]])
dL/db:  tensor([ 0.0815, -0.4603])
loss after 1 step optimization:  0.6904075145721436
w:  Parameter containing:
tensor([[-0.2218,  0.1986,  0.4819],
        [ 0.0535, -0.1476,  0.0343]], requires_grad=True)
b:  Parameter containing:
tensor([0.1916, 0.5354], requires_grad=True)


In [4]:
import torchvision.transforms as transforms
import torchvision

In [46]:
# trying input pipeline

# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

In [64]:
image, label = train_dataset[1]
print(image.size())
print(label)

# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = data_iter.next()
print(images.size())
print(len(labels))

for images, labels in train_loader:
    # Training code should be written here.
    pass


torch.Size([3, 32, 32])
9
torch.Size([64, 3, 32, 32])
64


In [10]:
# for custom dataset - batching and next iter elements

class CustomDataset():
    
    def __init__(self):
        super(CustomDataset, self).__init__()
        # initialise the file path and the variable labels if any
        pass
    def __getitem__(self, index):
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        
        pass
    def __len__(self):
        #return the length of dataset
        return  0
    
custom_dataset = CustomDataset()
#train_loader = torch.utils.data.DataLoader(dataset = custom_dataset,
#                                          batch_size=64,
#                                          shuffle=True)


    

In [11]:
#use of pre trained model

resnet = torchvision.models.resnet18(pretrained=True)
# for fine tune the top layer of the model, set as below.
for params in resnet.parameters():
    params.requires_grad = False

#replace the top layer for fine tuning 
resnet.fc = nn.Linear(resnet.fc.in_features,100)
# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)


Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to C:\Users\nitin.sharma9/.torch\models\resnet18-5c106cde.pth
86.1%

torch.Size([64, 100])


In [ ]:
# Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

# Save and load only the model parameter
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))